import { NextRequest, NextResponse } from "next/server"
import Anthropic from "@anthropic-ai/sdk"
import { notifyOwner } from "@/lib/jarvis/telegram"

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })
const GITHUB_TOKEN = process.env.GITHUB_TOKEN
const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY
const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL
const REPO = "Casellelol/JARVIS-brain"

type DigitalProductType = "ebook" | "prompt-pack" | "notion-template" | "swipe-file" | "checklist"

const TYPE_DESCRIPTIONS: Record<DigitalProductType, string> = {
  "ebook":           "a comprehensive, practical ebook with actionable advice",
  "prompt-pack":     "a collection of 20-30 high-value AI prompts with instructions",
  "notion-template": "a Notion template system with pages, databases, and instructions",
  "swipe-file":      "a curated swipe file of proven templates, scripts, and examples",
  "checklist":       "a professional checklist or SOP document with clear steps",
}

// Step 1: Generate product content using Claude
async function generateContent(type: DigitalProductType, topic: string): Promise<string> {
  const typeDesc = TYPE_DESCRIPTIONS[type] || "a useful digital resource"

  const response = await client.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 4000,
    messages: [{
      role: "user",
      content: `Create ${typeDesc} about: "${topic}".

Requirements:
- Genuinely useful, not generic fluff
- Formatted in clean Markdown
- Professional quality someone would pay £10-25 for
- Practical and actionable with real examples
- 800-1500 words for ebooks/swipe files, structured lists for prompts/checklists

Write the complete product content now:`,
    }],
  })

  return response.content[0].type === "text" ? response.content[0].text.trim() : ""
}

// Step 2: Push content to GitHub as a downloadable file
async function pushToGitHub(slug: string, content: string, title: string): Promise<string | null> {
  const path = `digital-products/${slug}.md`
  const fileContent = `# ${title}\n\n*Digital product by Caselle — automatically generated by JARVIS*\n\n---\n\n${content}`

  try {
    // Check if file exists
    const getRes = await fetch(
      `https://api.github.com/repos/${REPO}/contents/${path}`,
      { headers: { Authorization: `token ${GITHUB_TOKEN}`, Accept: "application/vnd.github.v3+json" } }
    )
    const existing = getRes.ok ? await getRes.json() as { sha: string } : null

    const putRes = await fetch(
      `https://api.github.com/repos/${REPO}/contents/${path}`,
      {
        method: "PUT",
        headers: { Authorization: `token ${GITHUB_TOKEN}`, "Content-Type": "application/json" },
        body: JSON.stringify({
          message: `JARVIS: publish digital product — ${title}`,
          content: Buffer.from(fileContent).toString("base64"),
          sha: existing?.sha,
        }),
      }
    )

    if (!putRes.ok) return null

    // Return raw GitHub URL (public repo)
    return `https://raw.githubusercontent.com/${REPO}/main/${path}`
  } catch { return null }
}

// Step 3: Create Stripe product + price + payment link
async function createStripePaymentLink(
  title: string,
  description: string,
  price: number,
  downloadUrl: string
): Promise<{ paymentLinkUrl: string; productId: string; priceId: string } | null> {
  if (!STRIPE_SECRET_KEY) return null

  try {
    // Create Stripe product
    const productRes = await fetch("https://api.stripe.com/v1/products", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${STRIPE_SECRET_KEY}`,
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: new URLSearchParams({
        name: title,
        description,
        "metadata[download_url]": downloadUrl,
        "metadata[type]": "digital_product",
        "metadata[created_by]": "JARVIS",
      }),
    })
    if (!productRes.ok) return null
    const product = await productRes.json() as { id: string }

    // Create price
    const priceRes = await fetch("https://api.stripe.com/v1/prices", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${STRIPE_SECRET_KEY}`,
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: new URLSearchParams({
        product: product.id,
        unit_amount: String(price),
        currency: "gbp",
      }),
    })
    if (!priceRes.ok) return null
    const stripePrice = await priceRes.json() as { id: string }

    // Create payment link — success redirects to download
    const linkRes = await fetch("https://api.stripe.com/v1/payment_links", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${STRIPE_SECRET_KEY}`,
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: new URLSearchParams({
        "line_items[0][price]": stripePrice.id,
        "line_items[0][quantity]": "1",
        "after_completion[type]": "redirect",
        "after_completion[redirect][url]": downloadUrl,
        "metadata[download_url]": downloadUrl,
        "metadata[product_title]": title,
      }),
    })
    if (!linkRes.ok) return null
    const link = await linkRes.json() as { url: string }

    return { paymentLinkUrl: link.url, productId: product.id, priceId: stripePrice.id }
  } catch { return null }
}

// Step 4: Register product in digital-products.md on GitHub
async function registerProduct(entry: string): Promise<void> {
  try {
    const path = "digital-products.md"
    const getRes = await fetch(
      `https://api.github.com/repos/${REPO}/contents/${path}`,
      { headers: { Authorization: `token ${GITHUB_TOKEN}`, Accept: "application/vnd.github.v3+json" } }
    )
    const existing = getRes.ok ? await getRes.json() as { content: string; sha: string } : null
    const current = existing
      ? Buffer.from(existing.content, "base64").toString("utf-8")
      : "# Digital Products\n*Published by JARVIS — autonomous digital product engine.*\n\n"

    await fetch(`https://api.github.com/repos/${REPO}/contents/${path}`, {
      method: "PUT",
      headers: { Authorization: `token ${GITHUB_TOKEN}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        message: "JARVIS: register digital product",
        content: Buffer.from(current + entry).toString("base64"),
        sha: existing?.sha,
      }),
    })
  } catch {}
}

export async function POST(req: NextRequest) {
  try {
    const { type = "ebook", topic, price = 997, description } = await req.json()

    if (!topic) {
      return NextResponse.json({ error: "topic required" }, { status: 400 })
    }

    const productType = type as DigitalProductType
    const slug = topic.toLowerCase().replace(/[^a-z0-9]/g, "-").replace(/-+/g, "-").slice(0, 50)
    const title = `${topic.charAt(0).toUpperCase()}${topic.slice(1)}`
    const productDescription = description || `${title} — instant digital download by Caselle`
    const date = new Date().toISOString().slice(0, 16).replace("T", " ")

    // Generate content
    const content = await generateContent(productType, topic)
    if (!content) {
      return NextResponse.json({ error: "Content generation failed" }, { status: 500 })
    }

    // Push to GitHub
    const downloadUrl = await pushToGitHub(slug, content, title)
    if (!downloadUrl) {
      return NextResponse.json({ error: "GitHub upload failed" }, { status: 500 })
    }

    // Create Stripe payment link
    const stripe = await createStripePaymentLink(title, productDescription, price, downloadUrl)

    // Register in product log
    const logEntry = `\n## ${title} — ${date}\n- Type: ${productType}\n- Slug: ${slug}\n- Price: £${(price / 100).toFixed(2)}\n- Download: ${downloadUrl}\n- Payment: ${stripe?.paymentLinkUrl || "Stripe not configured"}\n- Status: LIVE\n`
    await registerProduct(logEntry)

    // Notify owner on Telegram
    const priceDisplay = `£${(price / 100).toFixed(2)}`
    if (stripe?.paymentLinkUrl) {
      await notifyOwner(
        `📦 *JARVIS — New Digital Product Live*\n\n*${title}*\n\n*Type:* ${productType}\n*Price:* ${priceDisplay}\n*Buy:* ${stripe.paymentLinkUrl}\n*Download:* ${downloadUrl}\n\nProduct is live and selling autonomously. No action needed.`
      )
    } else {
      await notifyOwner(
        `📦 *JARVIS — Digital Product Created*\n\n*${title}* — ${productType} at ${priceDisplay}\n\nContent generated and stored. Stripe not configured — add \`STRIPE_SECRET_KEY\` to create payment links automatically.\n\n*Download:* ${downloadUrl}`
      )
    }

    // Notify JARVIS main brain
    fetch(`${BASE_URL}/api/jarvis`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        message: `JARVIS published digital product: "${title}" (${productType}) at ${priceDisplay}. Payment link: ${stripe?.paymentLinkUrl || "N/A"}. Update your memory.`,
      }),
    }).catch(() => {})

    return NextResponse.json({
      success: true,
      title,
      slug,
      type: productType,
      downloadUrl,
      paymentLinkUrl: stripe?.paymentLinkUrl || null,
      price: priceDisplay,
      stripeConfigured: !!stripe,
    })
  } catch (err) {
    return NextResponse.json({ error: String(err) }, { status: 500 })
  }
}
